"""Manual reproducible font delivery build: fonttools[woff]==4.65.0, brotli==1.2.0.
Original licensed full fonts retained verbatim; no changes to font metrics/outlines/hints.
"""
from pathlib import Path
import json,hashlib
from fontTools.ttLib import TTFont
from fontTools import subset
from fontTools.pens.recordingPen import DecomposingRecordingPen
P=Path(__file__).resolve().parents[1]
COMMON=set(range(0,0x370))|set(range(0x400,0x530))|set(range(0x2000,0x2070))|set(range(0x20a0,0x20d0))|set(range(0x2100,0x2150))
def ranges(cps):
 runs=[]
 for cp in sorted(cps):
  if runs and cp==runs[-1][1]+1:runs[-1][1]=cp
  else:runs.append([cp,cp])
 return ','.join('U+%X'%a+('-%X'%b if a!=b else '')for a,b in runs)
css=[];manifest=[]
for name,weight in [('Regular',400),('Medium',500),('SemiBold',600),('Bold',700)]:
 src=P/f'public/fonts/montserrat/Montserrat-{name}.woff2';dst=src.with_name(f'Montserrat-{name}.common.woff2')
 original=TTFont(src);cmap=original.getBestCmap();common=set(cmap)&COMMON;rare=set(cmap)-common
 font=TTFont(src,recalcBBoxes=False,recalcTimestamp=False);opt=subset.Options();opt.flavor='woff2';opt.layout_features=['*'];opt.name_IDs=['*'];opt.name_languages=['*'];opt.name_legacy=True;opt.glyph_names=True
 tool=subset.Subsetter(options=opt);tool.populate(unicodes=common);tool.subset(font);font.flavor='woff2';font.save(dst);new=TTFont(dst);assert set(new.getBestCmap())==common
 og=original.getGlyphSet();ng=new.getGlyphSet()
 for cp in common:
  a,b=cmap[cp],new.getBestCmap()[cp];assert original['hmtx'][a]==new['hmtx'][b]
  op=DecomposingRecordingPen(og);np=DecomposingRecordingPen(ng);og[a].draw(op);ng[b].draw(np);assert op.value==np.value
 for filename,points in [(src.name,rare),(dst.name,common)]:
  css.append('@font-face{font-family:"Montserrat";src:url("/fonts/montserrat/'+filename+'") format("woff2");font-style:normal;font-weight:'+str(weight)+';font-display:swap;unicode-range:'+ranges(points)+';}')
 manifest.append(dict(weight=weight,source=src.name,common=dst.name,sourceSha256=hashlib.sha256(src.read_bytes()).hexdigest(),commonSha256=hashlib.sha256(dst.read_bytes()).hexdigest(),sourceBytes=src.stat().st_size,commonBytes=dst.stat().st_size,commonCodepoints=sorted(common),fallbackCodepoints=sorted(rare),allCodepoints=sorted(cmap)))
for name,weight in [('Regular',400),('Medium',500),('SemiBold',600),('Bold',700)]:
 css.append('@font-face{font-family:"Montserrat Input Full";src:url("/fonts/montserrat/Montserrat-'+name+'.woff2") format("woff2");font-style:normal;font-weight:'+str(weight)+';font-display:swap;}')
css.append('input[type="text"],input[type="tel"],input[type="email"],textarea{font-family:"Montserrat Input Full","Montserrat",sans-serif!important;}')
css.append('@font-face{font-family:"Montserrat Breadcrumb Fallback";src:local("Arial"),local("Liberation Sans");size-adjust:114%;}')
(P/'src/styles/fonts-split.css').write_text('/* Generated by scripts/build-split-fonts.py. Full original fallback retained. */\n'+'\n'.join(css)+'\n')
(P/'data/design/font-subsets.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Verified cmap partition, contours and widths:',[(x['weight'],x['sourceBytes'],x['commonBytes'])for x in manifest])
